DROP TABLE IF EXISTS book;

CREATE TABLE book (
    book_id int NOT NULL,
    title text NOT NULL,
    isbn varchar(32) NOT NULL,
    publisher_id int NOT NULL,

    CONSTRAINT PK_book_book_id PRIMARY KEY(book_id)
);

--На данном этапе мы объявили book_id как простой integer, то есть он не будет увеличиваться автоматически

--Чтобы назначить SEQUENCE на поле book_id мы можем сделать так:

CREATE SEQUENCE IF NOT EXISTS book_book_id_seq --Это просто название последовательности
START WITH 1 OWNED BY book.book_id; --Начинается с 1 и назначаем его на поле book_id в таблице book
--По сути это происходит автоматически, когда мы указываем при создании таблицы типа serial


INSERT INTO book (title, isbn, publisher_id)
VALUES
('title','isbn',1); --При таком вводе данных мы получим ошибку

--Для того, чтобы не получать ошибку нужно навесить CONSTRAINT DEFAULT который если никто не вставляет ничего в это поле, вызывает функцию nextval() на созданной нами последовательности
ALTER TABLE book
ALTER COLUMN book_id SET DEFAULT nextval('book_book_id_seq');
--Это тоже по сути происходит автоматически, когда мы указываем при создании таблицы типа serial

SELECT * FROM book;

--Начиная с PostgreSQL 10 версии более продвинутым способом создания полей с автоинкрементом является немного другой подход с другим синтаксисом.
CREATE TABLE book (
    book_id int GENERATED ALWAYS AS IDENTITY NOT NULL,
    title text NOT NULL,
    isbn varchar(32) NOT NULL,
    publisher_id int NOT NULL,

    CONSTRAINT PK_book_book_id PRIMARY KEY(book_id)
);
--Когда мы используем ALWAYS мы запрещаем PostgreSQL давать возможность вставлять явно book_id при INSERT INTO
INSERT INTO book
VALUES
(3,'title','isbn',1); --Вот так делать не получится 



--Этот вариант почти тоже самое, что и просто указание serial, поэтому лучше использовать ALWAYS
CREATE TABLE book (
    book_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title text NOT NULL,
    isbn varchar(32) NOT NULL,
    publisher_id int NOT NULL,

    CONSTRAINT PK_book_book_id PRIMARY KEY(book_id)
);


--Также в полном синтаксисе мы вольны задавать дополнительные опции при создании
CREATE TABLE book (
    book_id int GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 2) NOT NULL,
    title text NOT NULL,
    isbn varchar(32) NOT NULL,
    publisher_id int NOT NULL,

    CONSTRAINT PK_book_book_id PRIMARY KEY(book_id)
);